### PR TITLE
missing config in ga.yaml

### PR DESCRIPTION
**Pull request by fmedery**
instances was missing from the default ga.yaml.

### CODE REVIEW

**Review by jmakuc — APPROVED** [review]
Thanks!

**Comment by aaronjameshorne** [comment]
Hello,

Any idea if the code will work with any major releases of the Datadog agent 7. There's also hot fix versions like 6.18 I am loooking to update.

**Comment by jmakuc** [comment]
HI Aaron

We haven't been able to update the code to be compatible with version 7
yet. All help is much appreciated :)

Best!

Jonathan Makuc

*Bit**haus Software Boutique*
# --------------------------------------------------------
0x77 bithaus.cl
0x74 +56994191736
0x3F Suecia 0142, Of 1204, Providencia, Santiago, Chile
Truth is out there

**Comment by aaronjameshorne** [comment]
Hi Jonathan,

I actually updated a production Datadogt collector agent to 6.18.0 and the ga.py runs just fine and submitted metric data to datadog. I do however get warnings regarding python 3 but I think this deals with libs not yet imported. Hope this gives you some insight if you are wondering how this works with major and non-major agent releases. Thanks again for your reply!

https://github.com/DataDog/datadog-agent/releases/tag/6.18.0

**Pull request merged**
